# Generated by Django 5.2.12 on 2026-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('before_image', models.ImageField(upload_to='before_after/')),
                ('after_image', models.ImageField(upload_to='before_after/')),
            ],
        ),
    ]
